site_name: ProcessWire Community Docs
pages:
- About these docs: index.md
- Official docs: official-docs.md
#- Introducing ProcessWire: intro.md
- Inst–∞llation: installation.md
#- Main concepts: concepts.md
#- Administration: administration.md
theme: readthedocs
